# Site settings
title: "@rbo"
email: rob@robmcelvenny.com
copyright_name: robmcelvenny.com
description: "Live Journal, portfolio, and works from Rob McElvenny"
twitter_username: cocoabro
github_username:  cocoabro
email_username:  robert.mcelvenny@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-102049437-1

# Build settings
markdown: kramdown
highlighter: rouge

kramdown: 
  input: GFM
  hard_wrap: false
  
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed, jekyll-seo-tag]
